name: Java CI with Docker Compose and Rest Assured - API Automation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 version
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Specify a valid distribution
          java-version: '17'

      - name:  Build with Maven (Skip Tests)
        run: mvn clean install -DskipTests=true

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d
          docker ps

      - name: Run Tests
        run: mvn test

      - name: Shut down Docker Compose
        run: docker compose down

      - name: Deploy to Render
        if: github.ref == 'refs/heads/master' && success()
        env:
            DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Triggering salesperson-api deployment to Render (cloud deployment)..."
          curl -X POST "$DEPLOY_HOOK_URL"
