name: Java CI with Docker Compose and Rest Assured - API Automation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
          docker ps

      - name: Run Tests
        run: mvn test

      - name: Shut down Docker Compose
        run: docker-compose down
